### ISSUE TITLE
Error en despliegue de librerías Leaflet

### ISSUE THREAD

**Issue by sergioedo** [geomatico/tmb-geoportal#24]
Al compilar y hacer correr el proyecto (desde cero), siguiendo el readme, me encuentro que al desplegar en local (browser) me faltan los siguientes recursos:

- http://localhost:8100/lib/leaflet/leaflet.js
- http://localhost:8100/lib/leaflet/leaflet.css
- http://localhost:8100/lib/angular-leaflet-directive/angular-leaflet-directive.min.js

Y puede que por lo anterior, también me falla la carga de:

- Refused to load the script 'http://localhost:35729/livereload.js?snipver=1' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' http://localhost:8100".
- Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module app.controllers due to:
Error: [$injector:modulerr] Failed to instantiate module leaflet-directive due to:
Error: [$injector:nomod] Module 'leaflet-directive' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.3/$injector/nomod?p0=leaflet-directive....

**Comment by oscarfonts** [comment]
Te faltó el "gulp copy", que copia los paquetes necesarios de node_modules a www/lib.
Reorganizaré el README para que sea más claro.

**Comment by oscarfonts** [comment]
Cierro y abro otra con lo del livereload (que es otro tema).
