### ISSUE TITLE
propertyName vs mandatory fields

### ISSUE THREAD

**Issue by sergioedo** [geomatico/tmb-geoportal#26]
Revisar los campos que se solicitan al API via propertyName, porque algunos atributos venían igualmente en la respuesta sin solicitarlos (mandatory fields de GeoServer, algunos no se pueden evitar) y ahora algunos de ellos no llegan (porque ya no son obligatorios y no se solicitan explícitamente).

Ejemplo en services.js:

function getStop(idLine, idStop) {
      var url = urlBase + "/linies/metro/" + idLine.toString() + "/estacions/" + idStop.toString();
      var request = createRequest(url, {
        propertyName: "CODI_ESTACIO,NOM_ESTACIO,**CODI_LINIA,**NOM_LINIA,NOM_TIPUS_ACCESSIBILITAT,GEOMETRY"
      });
      return( request.then( handleSuccess, handleError ) );
    }

En negrita el campo que debería solicitarse, sino da errores. Revisar a nivel general.

**Comment by sergioedo** [comment]
Please, echale un ojo rapido y fixealo en cuanto puedas ;)

**Comment by michogar** [comment]
Done!
