### ISSUE TITLE
El botón back devuelve a la planta anterior

### ISSUE THREAD

**Issue by michogar** [geomatico/tmb-geoportal#8]
El botón back se gestiona mediante la URL,al ir cambiando la URL con las plantas, el botón back no lleva a la "pantalla" anterior.

**Comment by oscarfonts** [comment]
Nuestro hack cambiaba la URL sin disparar eventos de cambio de estado (notify=false), pero $ionicHistory se vuelve loco, puesto que a veces comprueba las transiciones en función de si ha cambiado la URL, y otras en función de los eventos de cambio de estado.

Solución: cuando se navegue entre plantas dentro del mapa, no cambiar la URL. Serán cambios en el scope, no en el state.
